[package]
name = "pam-dirlock"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dirlock = { path = "../dirlock" }
pamsm = { version = "0.5.5", features = ["libpam"] }
