//! # D-Bus interface proxy for: `com.valvesoftware.Dirlock1`
//!
//! This code was generated by `zbus-xmlgen` `5.3.0` from D-Bus introspection data.
//! Source: `com.valvesoftware.Dirlock1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "com.valvesoftware.Dirlock1", assume_defaults = true)]
pub trait Dirlock1 {
    /// AddProtectorToPolicy method
    fn add_protector_to_policy(
        &self,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// CancelJob method
    fn cancel_job(&self, jobid: u32) -> zbus::Result<()>;

    /// ChangeProtectorPassword method
    fn change_protector_password(
        &self,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// ConvertDir method
    fn convert_dir(
        &self,
        dir: &str,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<u32>;

    /// CreateProtector method
    fn create_protector(
        &self,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<String>;

    /// EncryptDir method
    fn encrypt_dir(
        &self,
        dir: &str,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<String>;

    /// GetAllPolicies method
    fn get_all_policies(
        &self,
    ) -> zbus::Result<
        std::collections::HashMap<
            String,
            Vec<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>,
        >,
    >;

    /// GetAllProtectors method
    fn get_all_protectors(
        &self,
    ) -> zbus::Result<Vec<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>>;

    /// GetDirStatus method
    fn get_dir_status(
        &self,
        dir: &str,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// GetProtector method
    fn get_protector(
        &self,
        id: &str,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// JobStatus method
    fn job_status(&self, jobid: u32) -> zbus::Result<i32>;

    /// LockDir method
    fn lock_dir(&self, dir: &str) -> zbus::Result<Vec<String>>;

    /// RecoveryAdd method
    fn recovery_add(
        &self,
        dir: &str,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<String>;

    /// RecoveryRemove method
    fn recovery_remove(&self, dir: &str) -> zbus::Result<()>;

    /// RecoveryRestore method
    fn recovery_restore(
        &self,
        dir: &str,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// RemoveProtector method
    fn remove_protector(&self, protector_id: &str) -> zbus::Result<()>;

    /// RemoveProtectorFromPolicy method
    fn remove_protector_from_policy(
        &self,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// UnlockDir method
    fn unlock_dir(
        &self,
        dir: &str,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// VerifyProtectorPassword method
    fn verify_protector_password(
        &self,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<bool>;

    /// JobFailed signal
    #[zbus(signal)]
    fn job_failed(&self, jobid: u32, error: &str) -> zbus::Result<()>;

    /// JobFinished signal
    #[zbus(signal)]
    fn job_finished(&self, jobid: u32, keyid: &str) -> zbus::Result<()>;

    /// JobProgress signal
    #[zbus(signal)]
    fn job_progress(&self, jobid: u32, progress: i32) -> zbus::Result<()>;
}
