[package]
name = "pam-fscryptrs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fscrypt-rs = { path = "../fscrypt-rs" }
pamsm = { version = "0.5.5", features = ["libpam"] }
